export { ConnectionState, type ConnectionStore, createConnectionStore } from './connection';
export { type TransportAdapter } from './transport';
export { type KairoSession } from './session';
export { WebSocketTransportAdapter } from './websocket';
export { ResilientTransportAdapter, type ResilientTransportConfig } from './resilient-transport';
export { KairoClient, type KairoClientOptions } from './client';
export { ComputerManager, type ComputerProfile, type ComputerInstance } from './computer';
export {
  encodeEnvelope,
  decodeEnvelope,
  MessageKind,
  Opcode,
  type KairoEnvelope,
  HEADER_SIZE,
  MAGIC,
  PROTOCOL_VERSION,
} from './envelope';
export {
  encodeHandshakeInit,
  decodeHandshakeAck,
  encodeListDirectoryRequest,
  decodeListDirectoryResponse,
  encodeReadFileRequest,
  decodeReadFileResponse,
  encodeWriteFileRequest,
  decodeWriteFileResponse,
  encodeWatchRequest,
  decodeWatchResponse,
  decodeFileEvent,
  FileEventKind,
  encodeCreatePtyRequest,
  decodeCreatePtyResponse,
  encodePtyInput,
  decodePtyOutput,
  encodeResizePtyRequest,
  encodeClosePtyRequest,
  encodeAttachPtyRequest,
  decodeAttachPtyResponse,
  encodeListPtysRequest,
  decodeListPtysResponse,
  encodeGetMetricsRequest,
  decodeGetMetricsResponse,
  encodeListProcessesRequest,
  decodeListProcessesResponse,
  encodeKillProcessRequest,
  encodeListContainersRequest,
  decodeListContainersResponse,
  encodeManageContainerRequest,
  decodeManageContainerResponse,
  encodeContainerLogsRequest,
  decodeContainerLogsResponse,
  encodeListServicesRequest,
  decodeListServicesResponse,
  encodeManageServiceRequest,
  decodeManageServiceResponse,
  type HandshakeInitPayload,
  type HandshakeAckPayload,
  type FileEntry,
  type FileEventPayload,
  type KairoErrorPayload,
  type CreatePtyRequestPayload,
  type SystemMetrics,
  type ProcessInfo,
  type PtySessionInfo,
  type DockerContainer,
  ContainerAction,
  type SystemService,
  ServiceAction,
  type LinuxApp,
  type LaunchAppResponsePayload,
  type RemoteSurfaceInfo,
  encodeGetGpuInfoRequest,
  decodeGetGpuInfoResponse,
  encodeStartGpuStreamRequest,
  decodeStartGpuStreamResponse,
  encodeStopGpuStreamRequest,
  decodeStopGpuStreamResponse,
  encodeGpuStreamStatsRequest,
  decodeGpuStreamStats,
  type GpuDevicePayload,
  type GetGpuInfoResponsePayload,
  type StartGpuStreamRequestPayload,
  type StartGpuStreamResponsePayload,
  type GpuStreamStatsPayload,
} from './protocol';


