pub mod app_manager;
pub mod config;
pub mod fs;
pub mod gpu;
pub mod gui;
pub mod metrics;
pub mod process;
pub mod pty;
pub mod server;
pub mod session;
pub mod system;

pub use app_manager::{AppError, AppManager};
pub use config::AgentConfig;
pub use fs::{FilesystemHandler, FsError};
pub use gpu::{GpuError, GpuManager};
pub use gui::x11::X11Backend;
pub use gui::{GuiError, GuiInputEvent, RemoteGuiBackend, RemoteSurface, SurfaceLifecycleState};
pub use metrics::MetricsCollector;
pub use process::{ProcessError, ProcessManager};
pub use pty::{PtyError, PtyManager};
pub use server::Server;
pub use session::{Session, SessionError, SessionState};
pub use system::{SystemError, SystemManager};
